=== ballerina-platform/ballerina-lang/http/netty/component/src/main/resources/netty-transports.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2008-2014, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://wso2.com/schema/netty-transports/config"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="transports">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="listeners">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="listener" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="parameters" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="parameter" maxOccurs="unbounded" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string"
                                                                                  name="name" use="optional"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id"/>
                                    <xs:attribute type="xs:string" name="host" use="optional"/>
                                    <xs:attribute type="xs:short" name="port"/>
                                    <xs:attribute type="xs:byte" name="bossThreadPoolSize" use="optional"/>
                                    <xs:attribute type="xs:short" name="workerThreadPoolSize" use="optional"/>
                                    <xs:attribute type="xs:byte" name="execHandlerThreadPoolSize" use="optional"/>
                                    <xs:attribute type="xs:string" name="scheme" use="optional"/>
                                    <xs:attribute type="xs:string" name="keyStoreFile" use="optional"/>
                                    <xs:attribute type="xs:string" name="keyStorePass" use="optional"/>
                                    <xs:attribute type="xs:string" name="trustStoreFile" use="optional"/>
                                    <xs:attribute type="xs:string" name="trustStorePass" use="optional"/>
                                    <xs:attribute type="xs:string" name="certPass" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="senders">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sender"  maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType mixed="true">
                                    <xs:sequence>
                                        <xs:element name="parameters" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="parameter" maxOccurs="unbounded" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:simpleContent>
                                                                <xs:extension base="xs:string">
                                                                    <xs:attribute type="xs:string"
                                                                                  name="name" use="optional"/>
                                                                </xs:extension>
                                                            </xs:simpleContent>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="xs:string" name="id"/>
                                    <xs:attribute type="xs:string" name="scheme" use="optional"/>
                                    <xs:attribute type="xs:string" name="keyStoreFile" use="optional"/>
                                    <xs:attribute type="xs:string" name="keyStorePass" use="optional"/>
                                    <xs:attribute type="xs:string" name="trustStoreFile" use="optional"/>
                                    <xs:attribute type="xs:string" name="trustStorePass" use="optional"/>
                                    <xs:attribute type="xs:string" name="certPass" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ballerina-platform/ballerina-lang/http/netty/component/etc/conf/netty-transports.xml
<transports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://wso2.com/schema/netty-transports/config netty-transports.xsd"
            xmlns="http://wso2.com/schema/netty-transports/config">
    <listeners>
        <listener
                id="jaxrs-http"
                host="127.0.0.1"
                port="7777"
                bossThreadPoolSize="2"
                workerThreadPoolSize="250"
                execHandlerThreadPoolSize="60"/>

        <listener
                id="jaxrs-https"
                host="127.0.0.1"
                port="8888"
                bossThreadPoolSize="2"
                workerThreadPoolSize="250"
                execHandlerThreadPoolSize="60"
                scheme="https"
                keyStoreFile="repository/resources/security/cert.jks"
                keyStorePass="secret"
                certPass="secret"/>

        <listener
                id="netty-gw"
                host="0.0.0.0"
                port="9090"
                bossThreadPoolSize="4"
                workerThreadPoolSize="8"
                execHandlerThreadPoolSize="60">
            <parameters>
                <parameter name="disruptor.wait.strategy">PHASED_BACKOFF</parameter>
                <parameter name="disruptor.buffer.size">1</parameter>
                <parameter name="disruptor.count">1</parameter>
                <parameter name="disruptor.eventhandler.count">1</parameter>
            </parameters>
        </listener>
    </listeners>

    <senders>
        <sender
                id="netty-gw"
                scheme="https"
                keyStoreFile="repository/resources/security/cert.jks"
                trustStoreFile="repository/resources/security/cert.jks"
                trustStorePass="secret"
                keyStorePass="secret"
                certPass="secret">
        <parameters>
            <parameter name="connection.pool.count">0</parameter>
        </parameters>
        </sender>
    </senders>
</transports>
